# -*- coding: utf-8 -*-
"""[23z9] 职业接触限值（OEL）法规库维护页面专项自检
   覆盖：菜单入口与命名、顶部 KPI 与主入口、五步维护流程条、四个 Tab
   （数据来源 / 数据集版本 / 限值明细 / 版本对比与审核）、
   来源范围为「欧盟（EU）+ 中国」两套、限值类型语义槽位对齐（长期 / 短期 / 上限）、
   数据集版本审核动作（提交审核 / 发布 / 退回）、限值明细同一 CAS 跨来源跨版本并存、
   版本对比六类变更与审核动作、7 步导入向导（含 7 类数据校验演示、
   阻断项拦截、原文与结构化文件分开上传）、页面边界表述与运行时错误。"""
import os
from playwright.sync_api import sync_playwright

CHROME='/Users/dowell/Library/Caches/ms-playwright/chromium-1223/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'
URL='file://'+os.path.abspath('PLM3.0全系统演示原型.html')
passed=failed=0
def ok(value,message):
    global passed,failed
    if value: passed+=1;print('  ✔ '+message)
    else: failed+=1;print('  ✘ '+message)

with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=CHROME,args=['--no-sandbox'])
    page=browser.new_context(viewport={'width':1720,'height':1000}).new_page()
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
    page.goto(URL,wait_until='load');page.wait_for_timeout(800)

    def kpi(i):
        return page.evaluate("(i)=>document.querySelectorAll('#pageHost .kpi')[i].querySelector('b').innerText",i)
    def txt(sel='#pageHost'):
        return page.locator(sel).inner_text()

    print('=== 菜单入口与路由 ===')
    oelname=page.evaluate("()=>MENU.find(x=>x.id==='comp').children.find(x=>x.id==='law').children.find(y=>y.id==='law:oel').name")
    ok(oelname=='职业接触限值（OEL）','菜单项命名为「职业接触限值（OEL）」（在法规库维护下）')
    page.evaluate("()=>showPage('law:oel')");page.wait_for_timeout(400)
    ok(page.evaluate('curPage')=='law:oel','law:oel 可正常进入（沿用既有路由，未新增路由）')
    ok(page.locator('#pageHost .oel-page, #pageHost .law-page').count()>0,'页面保持法规库统一视觉风格（law-page / oel-page）')

    print('\n=== 顶部构成 ===')
    t=txt()
    for k in ['已覆盖国家 / 地区','已发布数据集','待审核版本','最近更新时间']:
        ok(k in t,'顶部展示「%s」'%k)
    ok(kpi(0)=='2','已覆盖国家 / 地区 = 2（欧盟（EU）+ 中国，本公司只做这两个市场）')
    ok(kpi(1)=='2' and kpi(2)=='2','已发布数据集 = 2 · 待审核版本 = 2')
    ok('2026-09-12' in kpi(3),'最近更新时间有值')
    ok(page.get_by_role('button',name='新建数据来源').count()==1,'主入口「新建数据来源」')
    ok(page.get_by_role('button',name='导入限值数据集').count()==1,'主入口「导入限值数据集」')
    ok(page.locator('.oel-flow .sf').count()==5,'以五步流程条体现「来源 → 版本 → 明细 → 对比 → 发布」')
    flow=txt('.oel-flow')
    ok(all(x in flow for x in ['官方来源','数据集版本','限值明细','版本对比','审核发布']),'五步命名与需求一致')
    ok('欧盟 / 中国官方清单' in flow,'流程条第 1 步写明来源范围为欧盟 / 中国')
    ok('OEL 不是一部单独法规' in t and '欧盟与中国' in t,'顶部写明 OEL 是多套官方限值清单（以数据集版本为单位维护）')
    for b in ['不自动从 PDF 中识别并直接发布数据','不自动判断哪套清单的限值更严格','不把两套市场的限值合并成一个值','不根据投放市场自动选择 OEL','不实现真实 AI 解析与法规网站监控']:
        ok(b in t,'边界声明：%s'%b)
    ok('只对齐语义、不换算数值' in t,'边界声明写明语义对齐只对齐类型、不换算数值')

    print('\n=== Tab 1：数据来源 ===')
    ok(page.locator('#oelTabs button').count()==4,'页面下设四个 Tab')
    ok([page.locator('#oelTabs button').nth(i).inner_text().strip() for i in range(4)]==['数据来源','数据集版本','限值明细','版本对比与审核'],'Tab 命名与顺序与需求一致')
    ok(page.locator('#oelTable thead th').count()==10,'数据来源表列数 9 + 操作')
    hd=page.locator('#oelTable thead').inner_text()
    for c in ['国家 / 地区','发布机构','官方清单名称','法律依据','官方链接','原文格式','更新频率','维护状态','最近检查时间']:
        ok(c in hd,'数据来源字段：%s'%c)
    ok(page.locator('#oelTable tbody tr').count()==2,'默认展示 2 条来源记录（欧盟（EU）+ 中国）')
    st=txt('#oelTable')
    ok(all(x in st for x in ['欧盟（EU）','中国']),'只保留欧盟与中国两套来源记录')
    ok('GBZ 2.1-2019' in st and 'IOELV' in st,'来源含两套官方清单名称')
    ok('98/24/EC' in st and '职业病防治法' in st,'写明欧盟与中国的法律依据')
    ok('德国' not in st and '英国' not in st and '法国' not in st and '西班牙' not in st,'不再维护其他国家（德 / 英 / 法 / 西）的来源记录')
    ok('PDF' in st,'原文格式如实标注为 PDF / 网页（无官方结构化下载）')
    ok('原文格式决定维护方式' in t and '本次不实现真实的 PDF / 网页解析' in t,'说明原文格式与维护方式的关系')
    page.fill('#oelSrcKw','GBZ');page.wait_for_timeout(150)
    ok(page.locator('#oelTable tbody tr').count()==1,'支持关键词搜索（GBZ → 1 条）')
    page.fill('#oelSrcKw','');page.wait_for_timeout(120)
    page.locator('#oelTable tbody tr').first.click();page.wait_for_timeout(250)
    d=txt('#oelDw')
    ok('法律依据' in d and '更新频率' in d and '已建版本数' in d and '最新版本' in d,'来源详情抽屉展示依据 / 频率 / 已建版本')
    ok('每套官方清单单独建立来源记录' in d,'抽屉写明来源不合并')
    ok('本公司仅覆盖欧盟与中国两个市场' in d and '其他国家级清单暂不建立' in d,'来源说明写明只覆盖欧盟与中国两个市场')
    page.evaluate('oelDrawerClose()');page.wait_for_timeout(150)
    page.get_by_role('button',name='新建数据来源').click();page.wait_for_timeout(250)
    page.fill('#oelNsRg','韩国');page.fill('#oelNsOrg','雇佣劳动部（MOEL）')
    page.fill('#oelNsList','化学物质职业接触限值清单')
    page.get_by_role('button',name='保存来源').click();page.wait_for_timeout(300)
    ok(page.locator('#oelTable tbody tr').count()==3,'新建数据来源后来源数 2 → 3（能力保留，本期不建其他国家数据）')
    ok(kpi(0)=='2','新建来源但尚未建数据集时「已覆盖国家 / 地区」不变（按已建数据集计）')
    ok(oelname=='职业接触限值（OEL）','（复核）菜单命名未被页面重渲染影响')

    print('\n=== Tab 2：数据集版本 ===')
    page.locator('#oelTabs button').nth(1).click();page.wait_for_timeout(300)
    ok(page.locator('#oelTable thead th').count()==13,'数据集版本表列数 12 + 操作')
    hd2=page.locator('#oelTable thead').inner_text()
    for c in ['数据集名称','国家 / 地区','版本号','发布日期','生效日期','失效日期','原文附件','结构化数据附件','数据条数','状态','维护人','版本说明']:
        ok(c in hd2,'数据集版本字段：%s'%c)
    ok(page.locator('#oelTable tbody tr').count()==6,'默认展示全部 6 个版本（欧盟 3 + 中国 3）')
    opts=page.evaluate("()=>[...document.querySelectorAll('#oelSetSt option')].map(o=>o.textContent)")
    ok(all(x in opts for x in ['草稿','待审核','已发布','已失效']),'状态筛选覆盖草稿 / 待审核 / 已发布 / 已失效')
    sts=page.evaluate("()=>OEL_SETS.map(s=>s.st)")
    ok(all(x in sts for x in ['草稿','待审核','已发布','已失效']),'数据集版本状态覆盖四种')
    ok(page.evaluate("()=>OEL_SETS.filter(s=>s.rg==='欧盟（EU）').length")==3 and page.evaluate("()=>OEL_SETS.filter(s=>s.rg==='中国').length")==3,'版本只归属欧盟与中国两个来源（各 3 个版本）')
    page.select_option('#oelSetSt','待审核');page.wait_for_timeout(250)
    ok(page.locator('#oelTable tbody tr').count()==2,'按状态筛选：待审核 2 个版本（欧盟 V2027.1 / 中国送审稿）')
    ok(page.locator('#oelTable tbody tr').first.get_by_role('button',name='发布').count()==1,'待审核版本提供「发布」操作')
    ok(page.locator('#oelTable tbody tr').first.get_by_role('button',name='退回').count()==1,'待审核版本提供「退回」操作')
    ok(page.locator('#oelTable tbody tr').first.get_by_role('button',name='版本对比').count()==1,'待审核版本提供「版本对比」入口')
    ok(page.locator('#oelTable tbody tr').first.get_by_role('button',name='查看明细').count()==1,'提供「查看明细」入口')
    page.locator('#oelTable tbody tr').filter(has_text='送审稿').first.get_by_role('button',name='发布').click()
    page.wait_for_timeout(350)
    ok(page.locator('#oelTable tbody tr').count()==1,'发布后该版本离开「待审核」（剩 1 条）')
    ok(kpi(1)=='3' and kpi(2)=='1','已发布数据集 2 → 3，待审核 2 → 1')
    page.select_option('#oelSetSt','草稿');page.wait_for_timeout(250)
    ok(page.locator('#oelTable tbody tr').count()==1,'草稿状态 1 个版本（中国 2027 版）')
    page.locator('#oelTable tbody tr').first.get_by_role('button',name='提交审核').click();page.wait_for_timeout(350)
    ok(page.evaluate("()=>OEL_SETS.filter(s=>s.st==='草稿').length")==0,'提交审核后草稿清零')
    ok('没有匹配的记录' in txt('#oelTable'),'草稿筛选下列表为空（状态已流转）')
    ok(kpi(2)=='2','待审核回到 2（草稿 → 待审核流转正确）')
    page.select_option('#oelSetSt','');page.wait_for_timeout(250)
    ok(page.locator('#oelTable tbody tr').count()==6,'清空筛选后恢复全部 6 个版本')
    t2=txt()
    ok('原始 PDF 或网页存档与结构化 Excel 分开保存' in t2,'写明原文存档与结构化数据分开保存')
    ok('以「完整清单版本」为单位维护' in t2,'写明以完整清单版本为单位维护')
    ok('不逐条新增 / 修改单个物质' in t2,'写明不逐条维护单个物质')
    ok('待审核版本不参与合规判断' in t2,'写明待审核版本不参与合规判断')

    print('\n=== Tab 3：限值明细 ===')
    page.locator('#oelTabs button').nth(2).click();page.wait_for_timeout(300)
    t=txt()
    ok(page.locator('#oelTable thead th').count()==20,'限值明细表列数 19 + 操作（新增「语义槽位」列）')
    hd3=page.locator('#oelTable thead').inner_text()
    for c in ['所属数据集版本','国家 / 地区','CAS 号','EC 号','物质名称','限值类型','语义槽位','长期限值 TWA',
              '短期限值 STEL','峰值 / Ceiling','数值单位','皮肤标记','致敏标记','生物监测标记',
              '其他官方标记','适用范围','原文备注或脚注','生效日期','数据状态']:
        ok(c in hd3,'限值明细字段：%s'%c)
    ok(page.locator('#oelTable tbody tr').count()==8,'默认分页 8 条/页（共 16 条示例明细）')
    ok(page.evaluate("()=>OEL_LIMITS.length")==16,'示例明细共 16 条，只归属欧盟与中国两套来源')
    page.fill('#oelLimKw','108-88-3');page.wait_for_timeout(250)
    ok(page.locator('#oelTable tbody tr').count()==3,'同一 CAS（甲苯 108-88-3）跨来源跨版本并存 3 条')
    nats=page.evaluate("()=>[...document.querySelectorAll('#oelTable tbody tr')].map(r=>r.children[1].innerText)")
    ok(sorted(nats)==sorted(['欧盟（EU）','欧盟（EU）','中国']),'3 条记录分属欧盟两个版本与中国一个版本，互不覆盖')
    tv=page.evaluate("()=>[...document.querySelectorAll('#oelTable tbody tr')].map(r=>r.children[7].innerText+r.children[8].innerText)")
    ok(len(set(tv))>1,'同一 CAS 各来源限值数值不同且同时保留（未合并为一个值）')
    kd=page.evaluate("()=>[...document.querySelectorAll('#oelTable tbody tr')].map(r=>r.children[6].innerText)")
    ok(all('长期' in x for x in kd),'语义槽位列标注每条记录的槽位归属')
    page.fill('#oelLimKw','');page.wait_for_timeout(200)
    page.select_option('#oelLimKind','CEIL');page.wait_for_timeout(250)
    ok(page.locator('#oelTable tbody tr').count()==1,'按语义槽位筛选（上限 → 1 条：中国甲醛 MAC）')
    ok('MAC' in txt('#oelTable'),'上限槽位对应中国 MAC 口径')
    page.select_option('#oelLimKind','');page.wait_for_timeout(200)
    page.select_option('#oelLimSet','DS-CN-1901');page.wait_for_timeout(250)
    ok(page.locator('#oelTable tbody tr').count()==7,'按数据集版本筛选（中国 GBZ 2.1-2019 → 7 条）')
    ok('CN·GBZ 2.1-2019' in txt('#oelTable'),'记录带所属数据集版本标识')
    page.select_option('#oelLimRg','中国');page.wait_for_timeout(250)
    ok(page.locator('#oelTable tbody tr').count()==7,'按国家筛选（中国）与数据集筛选可叠加')
    ok('PC-TWA + PC-STEL' in txt('#oelTable') or 'MAC' in txt('#oelTable'),'中国记录限值类型为 PC-TWA / PC-STEL / MAC 口径')
    page.select_option('#oelLimSet','');page.wait_for_timeout(200)
    page.select_option('#oelLimType','MAC');page.wait_for_timeout(250)
    ok(page.locator('#oelTable tbody tr').count()==1,'按限值类型筛选（MAC → 1 条：甲醛）')
    page.select_option('#oelLimType','');page.select_option('#oelLimRg','');page.wait_for_timeout(250)
    page.get_by_role('button',name='限值类型字典').click();page.wait_for_timeout(300)
    dk=txt('#oelDw')
    ok(page.locator('#oelDw tbody tr').count()==6,'限值类型字典列出 6 条映射（中国 3 类 + 欧盟 3 行）')
    for x in ['PC-TWA','PC-STEL','MAC','8h TWA','STEL']:
        ok(x in dk,'字典含原文类型：%s'%x)
    ok('只对齐语义' in dk and '不改数值' in dk,'字典声明只对齐语义、不改数值')
    ok('为什么不做数值归一' in dk and 'ppm 换算' in dk,'字典说明为什么不做数值归一（换算假设 + 口径搬运）')
    page.evaluate('oelDrawerClose()');page.wait_for_timeout(150)
    page.fill('#oelLimKw','1330-20-7');page.wait_for_timeout(250)
    page.locator('#oelTable tbody tr').first.click();page.wait_for_timeout(300)
    d3=txt('#oelDw')
    ok('同一 CAS 在其它来源 / 版本的记录' in d3 and '并存不覆盖' in d3,'明细抽屉列出同一 CAS 的其它来源 / 版本记录')
    ok('语义槽位' in d3 and '槽位只用于' in d3,'明细抽屉展示语义槽位与对齐说明')
    ok('皮 · 可经皮肤吸收' in d3,'展示皮肤标记口径')
    ok('原文备注或脚注' in d3,'展示原文备注 / 脚注')
    ok('系统不合并、不排序、不判断' in d3,'明细抽屉声明不合并 / 不判断更严格')
    page.evaluate('oelDrawerClose()');page.wait_for_timeout(150)
    ok('同一 CAS 在不同来源、不同版本中的记录必须同时存在，不能互相覆盖' in t,'页面声明同一 CAS 跨来源记录必须并存')
    ok('限值类型口径不同，比对前须先确认口径' in t and 'MAC' in t and 'PC-TWA' in t,'页面说明国内外限值类型口径差异')
    ok('限值类型字典' in t and '只对齐语义、不换算数值' in t,'页面说明语义槽位只做类型对齐')

    print('\n=== Tab 4：版本对比与审核 ===')
    page.locator('#oelTabs button').nth(3).click();page.wait_for_timeout(300)
    t=txt()
    ok(page.locator('.oel-diffbar .dt').count()==6,'变更类型计数覆盖六类（新增 / 删除 / 数值 / 单位 / 标记 / 备注）')
    ok(page.locator('#oelTable tbody tr').count()==6,'默认对比会话（欧盟 IOELV V2026.1 → V2027.1）6 条变更')
    hd4=page.locator('#oelTable thead').inner_text()
    for c in ['变更类型','CAS 号','物质名称','变更字段','语义槽位','变更前','变更后','变化说明','数据状态']:
        ok(c in hd4,'版本对比字段：%s'%c)
    ok('本 Tab 的对比结果为演示样例数据' in t,'显式标注对比结果为演示样例数据')
    ok('必须经法规专员审核后发布' in t,'写明版本变化须人工审核后发布')
    ok(page.locator('#oelTable tbody tr').first.inner_text().find('长期')>=0,'变更行标注涉及的语义槽位')
    page.select_option('#oelCmpTp','新增物质');page.wait_for_timeout(250)
    ok(page.locator('#oelTable tbody tr').count()==1,'按变更类型筛选（新增物质 → 1 条）')
    page.select_option('#oelCmpTp','');page.wait_for_timeout(200)
    page.select_option('#oelCmpSel','B');page.wait_for_timeout(300)
    ok(page.locator('#oelTable tbody tr').count()==4,'切换对比会话（中国 GBZ 2.1-2019 → 2026 送审稿）4 条变更')
    ok('PC-TWA' in txt('#oelTable'),'中国会话展示国内限值口径变化')
    page.locator('#oelTable tbody tr').first.get_by_role('button',name='查看变更详情').click();page.wait_for_timeout(300)
    d4=txt('#oelDw')
    ok('变更前' in d4 and '变更后' in d4 and '法规出处' in d4,'变更详情展示前后对照与法规出处')
    ok('语义槽位' in d4,'变更详情展示涉及的语义槽位')
    ok('本次不实现自动影响分析' in d4 and '不自动得出' in d4,'变更详情声明不做自动影响分析')
    page.evaluate('oelDrawerClose()');page.wait_for_timeout(150)
    page.get_by_role('button',name='退回修改').click();page.wait_for_timeout(350)
    ok(page.locator('#oelTable tbody tr').first.inner_text().find('已退回')>=0,'退回修改后变更状态变为「已退回」')
    ok(kpi(1)=='2' and kpi(2)=='2','退回后：已发布 2 · 待审核 2（目标版本回到草稿）')
    page.select_option('#oelCmpSel','A');page.wait_for_timeout(300)
    page.get_by_role('button',name='审核通过并发布新版本').click();page.wait_for_timeout(350)
    ok(page.locator('#oelTable tbody tr').first.inner_text().find('已通过')>=0,'审核通过后变更状态变为「已通过」')
    ok(kpi(1)=='3' and kpi(2)=='1','欧盟会话审核通过并发布后：已发布 3 · 待审核 1')

    print('\n=== 导入限值数据集 · 7 步向导 ===')
    page.get_by_role('button',name='导入限值数据集').click();page.wait_for_timeout(350)
    ok('第 1 步 / 共 7 步' in txt('#mFoot'),'向导共 7 步')
    ok(page.locator('.oel-mini .mini-step').count()==7,'步骤条含 7 个节点（选择来源 → 版本信息 → 上传 → 解析 → 校验 → 比较 → 提交）')
    ok(page.locator('#oiSrc option').count()==3,'第 1 步可选数据来源（欧盟 / 中国 + 新建的韩国来源，共 3 项）')
    ok('来源与版本不合并' in txt('#mBody'),'第 1 步说明来源与版本不合并')
    page.get_by_role('button',name='下一步：填写版本信息').click();page.wait_for_timeout(250)
    ok('第 2 步 / 共 7 步' in txt('#mFoot'),'第 2 步：填写版本信息')
    for f in ['oiName','oiVer','oiPub','oiEff','oiOwner']:
        ok(page.locator('#'+f).count()==1,'第 2 步字段：%s'%f)
    page.fill('#oiVer','V2028.1')
    page.get_by_role('button',name='下一步：上传附件').click();page.wait_for_timeout(250)
    ok('第 3 步 / 共 7 步' in txt('#mFoot'),'第 3 步：上传附件')
    ok(page.locator('.oel-split .drop').count()==2,'原文附件与结构化数据双栏分开上传')
    ok('① 原文附件' in txt('#mBody') and '② 结构化数据文件' in txt('#mBody'),'双栏分别标注原文附件 / 结构化数据文件')
    ok(page.locator('#oiNext3').is_disabled(),'未上传结构化数据时无法进入下一步')
    page.get_by_text('使用结构化示例文件').click();page.wait_for_timeout(300)
    ok(page.locator('#oiXlsRow .file-row').count()==1,'结构化数据文件已就位')
    ok(not page.locator('#oiNext3').is_disabled(),'上传后解除拦截')
    ok('系统不自动从 PDF 识别并直接发布数据' in txt('#mBody'),'第 3 步重申不从 PDF 自动识别并发布')
    page.get_by_role('button',name='下一步：解析预览').click();page.wait_for_timeout(250)
    ok('第 4 步 / 共 7 步' in txt('#mFoot') and '识别数据行数' in txt('#mBody'),'第 4 步：解析预览')
    ok(page.locator('#mBody table tbody tr').count()==5,'预览展示解析结果行')
    ok('语义槽位' in txt('#mBody'),'解析预览一并给出语义槽位对齐结果')
    page.get_by_role('button',name='下一步：数据校验').click();page.wait_for_timeout(300)
    ok('第 5 步 / 共 7 步' in txt('#mFoot'),'第 5 步：数据校验')
    ok(page.locator('#mBody .oel-check .ck').count()==7,'校验结果覆盖 7 类规则')
    ct=txt('#mBody')
    for c in ['CAS 格式错误','物质名称缺失','数值存在但单位缺失','同一数据集内重复记录','生效日期冲突','无法识别的物质标记','与上一版本相比发生重大变化']:
        ok(c in ct,'校验规则：%s'%c)
    ok('阻断项（必须处理）' in ct and '告警项（须确认）' in ct and '提示项（仅记录）' in ct,'校验结果分级（阻断 / 告警 / 提示）')
    ok('校验通过项' in ct and '必填列完整性' in ct and '语义槽位' in ct,'同时展示校验通过项（含语义槽位映射通过）')
    ok(page.locator('#oiNext5').is_disabled(),'存在阻断项时无法进入下一步')
    ok('仍有' in ct and '条阻断项未处理' in ct,'提示未处理阻断项数量')
    for i in range(7):
        page.locator('#mBody .oel-check .ck .hd button').first.click();page.wait_for_timeout(120)
    ok(page.locator('#mBody .oel-check .ck.done').count()==7,'逐条「标记为已处理」留痕')
    ok(not page.locator('#oiNext5').is_disabled(),'阻断项处理后解除拦截')
    page.get_by_role('button',name='下一步：与上一版本比较').click();page.wait_for_timeout(300)
    ok('第 6 步 / 共 7 步' in txt('#mFoot'),'第 6 步：与上一版本比较')
    c6=txt('#mBody')
    for c in ['新增物质','删除物质','长期 / 短期限值变化','单位 / 口径变化','标记变化','备注 / 适用范围变化']:
        ok(c in c6,'版本比较统计：%s'%c)
    ok(page.locator('#mBody table tbody tr').count()==5,'比较结果展示差异行')
    ok('语义槽位' in c6,'比较结果给出差异涉及的语义槽位')
    ok('不自动判断受影响范围' in c6 or '仅为提示' in c6,'写明对比结果仅为提示、不做自动判断')
    page.get_by_role('button',name='下一步：提交审核').click();page.wait_for_timeout(250)
    ok('第 7 步 / 共 7 步' in txt('#mFoot'),'第 7 步：提交审核')
    ok('待审核' in txt('#mBody') and '结构化附件' in txt('#mBody'),'提交前汇总来源 / 版本 / 附件 / 校验结果')
    page.locator('#oiOk').check();page.wait_for_timeout(150)
    page.get_by_role('button',name='提交审核').click();page.wait_for_timeout(400)
    ok(page.evaluate("()=>OEL_SETS.length")==7,'提交后数据集版本 6 → 7')
    ok(page.evaluate("()=>OEL_SETS[0].st")=='待审核','新版本初始状态为「待审核」')
    ok('待审核' in txt('#oelTable'),'列表可见新提交的待审核版本')
    ok(kpi(2)=='2','待审核版本数随之更新')

    print('\n=== 表述红线 ===')
    allp=txt('#pageHost')+txt('#oelDw') if page.locator('#oelDw').count() else txt('#pageHost')
    ok('已实现自动监控' not in allp and '自动抓取' not in allp,'无「已实现自动监控 / 自动抓取」类表述')
    ok('不实现真实 AI 解析' in allp,'明确标注不实现真实 AI 解析与法规网站监控')
    ok('后续统一实现' in allp and 'SDS 第 8 节' in allp,'写明投放市场 → 有效法规版本 → SDS 第 8 节关联后续统一实现')
    ok('德国' not in allp and '英国' not in allp and '法国' not in allp and '西班牙' not in allp,'页面不再出现其他国家来源表述')

    print('\n=== 运行时 ===')
    ok(not errors,'OEL 页面全流程 JavaScript 错误为 0'+(('：'+errors[0]) if errors else ''))
    browser.close()

print('=== 结果：通过 %d / 失败 %d ==='%(passed,failed))
