# -*- coding: utf-8 -*-
"""[23z7 / 23z8] REACH 法规库统一页面 + 合规管理菜单调整专项自检
   覆盖：菜单结构（法规库维护 6 入口 / 外部参考数据分组 / 受限物质管理分组）、
   REACH 顶部法规主信息、6 个 Tab（SDS 编制要求 16 章 / SVHC 候选清单 /
   Annex XIV 授权清单 / Annex XVII 限制清单 / Annex XIII PBT-vPvB 判定规则卡片 /
   版本变更与影响）、各 Tab 数据版本信息条、详情抽屉、
   跳转法规统一查询（按 lawKey 过滤）、五步导入向导、
   RoHS 限用物质页（10 条全列 / 人工维护口径 / 豁免入口 / 中国 RoHS 待确认）、
   运输法规库占位页（多运输方式）、OEL 页面入口、表述红线。"""
import os
from playwright.sync_api import sync_playwright

CHROME='/Users/dowell/Library/Caches/ms-playwright/chromium-1223/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'
URL='file://'+os.path.abspath('PLM3.0全系统演示原型.html')
passed=failed=0
def ok(value,message):
    global passed,failed
    if value: passed+=1;print('  ✔ '+message)
    else: failed+=1;print('  ✘ '+message)

with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=CHROME,args=['--no-sandbox'])
    page=browser.new_context(viewport={'width':1720,'height':1000}).new_page()
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
    page.goto(URL,wait_until='load');page.wait_for_timeout(800)

    print('=== 菜单结构 ===')
    comp=page.evaluate("()=>MENU.find(x=>x.id==='comp').children.map(x=>({id:x.id,name:x.name,children:(x.children||[]).map(y=>y.id)}))")
    law=next(x for x in comp if x['id']=='law')
    lawnames=page.evaluate("()=>MENU.find(x=>x.id==='comp').children.find(x=>x.id==='law').children.map(y=>y.name)")
    ok(law['children']==['law:clp','law:reach','law:oel','law:trans','law:cn','law:zdhc'],'法规库维护 6 个入口（CLP / REACH / OEL / 运输 / 国内危化品 / ZDHC）')
    ok(lawnames==['CLP 法规库','REACH 法规库','职业接触限值（OEL）','运输法规库','国内危化品法规库','ZDHC MRSL'],'菜单命名与需求一致（REACH 法规库 / 职业接触限值（OEL）/ 国内危化品法规库）')
    ok('REACH / RoHS' not in ' '.join(lawnames),'菜单中不再出现「REACH / RoHS」合并命名')
    ext=next(x for x in comp if x['id']=='ext')
    ok(ext['name']=='外部参考数据' and ext['children']==['law:cl'],'C&L Inventory 移至「外部参考数据」分组')
    subst=next(x for x in comp if x['id']=='subst')
    ok(subst['name']=='受限物质管理' and subst['children']==['subst:list','law:rohs'],'「受限物质管理」下含受限物质清单 + RoHS 限用物质')
    ok(lawnames[-1]=='ZDHC MRSL','ZDHC MRSL 本期维持现状（仍在法规库维护下）')
    page.evaluate("showPage('law:reach')");page.wait_for_timeout(400)
    ok(page.evaluate('curPage')=='law:reach','law:reach 可正常进入（沿用既有路由）')

    print('\n=== 顶部法规主信息 ===')
    text=page.locator('#pageHost').inner_text()
    ok('REACH 法规库' in text and 'REACH Regulation' in text and 'Regulation (EC) No 1907/2006' in text,'展示法规名称与编号')
    ok('欧盟' in text and '已发布' in text,'展示适用市场与当前状态')
    ok(page.locator('#pageHost .ev').count()>0 and '复审预警' in text,'顶部展示证据灯')
    ok('REACH 主版本' in text and '合并文本' in text,'展示当前法规版本（合并文本日期）')
    ok('EUR-Lex' in text,'展示官方来源 EUR-Lex')
    ok('当前发布状态' in text,'展示当前发布状态')
    ok('最近检查时间' in text and '最近审核时间' in text and '审核人' in text and '数据截止日期' in text,'展示检查 / 审核 / 审核人 / 数据截止日期')
    ok('质管-熊倩' in text and 'SVHC 每年 1 月 / 7 月各一批' in text,'展示维护责任人与更新频率')
    for f in ['SDS 编制','第 15 章法规判断','受限物质查询']:
        ok(f in text,'影响功能包含「%s」'%f)
    ok('REACH 管注册、授权与限制' in text and '本页面仅涉及 REACH' in text,'法制定位说明（REACH / CLP 分工）')
    ok('RoHS 限用物质' in text and '拆分' in text and 'C&L Inventory' in text and '外部参考数据' in text,'标注 RoHS 与 C&L Inventory 不并入本页')

    print('\n=== Tab 切换（顶部主信息保持不变） ===')
    tabs=page.locator('#rchTabs button')
    ok(tabs.count()==6,'共 6 个 Tab')
    for k,label in [('sds','SDS 编制要求'),('svhc','SVHC 候选清单'),('xiv','Annex XIV'),('xvii','Annex XVII'),('pbt','Annex XIII PBT/vPvB'),('chg','版本变更与影响')]:
        page.evaluate("(k)=>{var b=document.querySelectorAll('#rchTabs button');for(var x of b){if(x.getAttribute('data-key')===k)x.click();}}",k)
        page.wait_for_timeout(150)
        ok(page.evaluate('()=>_rchTab')==k,'切到 %s'%label)
    ok('影响功能' in page.locator('#pageHost').inner_text(),'切 Tab 后顶部主信息仍在')

    print('\n=== Tab1 SDS 编制要求（16 章） ===')
    page.evaluate("()=>{_rchF.sds={kw:'',mode:''};rchGoTab('sds');}");page.wait_for_timeout(200)
    ok(page.evaluate("()=>REACH_SDS_CH.length")==16,'覆盖 REACH Annex II 全部 16 章')
    ok(page.evaluate("()=>REACH_SDS_CH.filter(x=>x.req!=='必填').length")==3,'含 3 个条件必填章节')
    ok(page.locator('#rchTable tbody tr').count()==8,'第 1 页 8 条（每页 8 条）')
    head=page.locator('#rchTable thead').inner_text()
    for c in ['章节编号','章节名称','是否必填','数据来源','生成方式','法规出处','状态']:
        ok(c in head,'列表含「%s」列'%c)
    body=page.locator('#rchTabBody').inner_text()
    ok('Article 31' in body and 'Annex II' in body and 'CLP' in body,'三条法规依据分工写明（Article 31 / Annex II / CLP）')
    ok('何时必须提供 SDS' in body and '系统不判断产品是否需要编制 SDS' in body,'业务边界写明（系统不判断是否需要 SDS）')
    strip=page.locator('.law-strip').first.inner_text()
    ok('Annex II' in strip and '生效日期' in strip and '来源文件' in strip,'Tab1 信息条展示数据版本 / 生效日期 / 来源文件')
    page.fill('#rchSdsKw','运输');page.wait_for_timeout(150)
    ok(page.locator('#rchTable tbody tr').count()==1 and '运输信息' in page.locator('#rchTable tbody').inner_text(),'支持按章节名称搜索')
    page.fill('#rchSdsKw','');page.wait_for_timeout(120)
    page.evaluate("(x)=>rchSdsDrawer(x)",'14');page.wait_for_timeout(250)
    dw=page.locator('#rchDw').inner_text()
    ok('研发实现用' in dw,'抽屉标注「研发实现用」')
    ok('子章节' in dw and '字段要求摘要' in dw and '对应系统字段' in dw and '模板版本' in dw,'抽屉含子章节 / 字段要求 / 系统字段 / 模板版本')
    ok('运输法规库' in dw and '不受运输法规管制' in dw,'第 14 章指向运输法规库并写明条件必填口径')
    page.evaluate("()=>rchDrawerClose()")

    print('\n=== Tab2 SVHC 候选清单 ===')
    page.evaluate("()=>{_rchF.svhc={kw:'',reason:''};rchGoTab('svhc');}");page.wait_for_timeout(200)
    head=page.locator('#rchTable thead').inner_text()
    for c in ['物质名称','CAS 号','EC 号','列入日期','列入原因','适用浓度提示','当前版本','官方来源','状态']:
        ok(c in head,'列表含「%s」列'%c)
    page.fill('#rchSvKw','85535-84-8');page.wait_for_timeout(150)
    ok(page.locator('#rchTable tbody tr').count()==1 and '短链氯化石蜡' in page.locator('#rchTable tbody').inner_text(),'支持按 CAS 搜索')
    page.fill('#rchSvKw','');page.wait_for_timeout(120)
    page.select_option('#rchSvRsn','PBT');page.wait_for_timeout(150)
    ok(page.locator('#rchTable tbody tr').count()==1,'支持按列入原因筛选')
    page.select_option('#rchSvRsn','');page.wait_for_timeout(120)
    page.evaluate("()=>rchSvhcDrawer('50-00-0')");page.wait_for_timeout(250)
    dw=page.locator('#rchDw').inner_text()
    ok('0.1%' in dw and '信息传递' in dw,'抽屉写明 0.1% 浓度触发信息传递义务')
    ok('演示示例数据' in dw,'抽屉标注示例数据口径')
    page.evaluate("()=>rchDrawerClose()")

    print('\n=== Tab3 Annex XIV 授权清单 ===')
    page.evaluate("()=>{_rchF.xiv={kw:'',st:''};rchGoTab('xiv');}");page.wait_for_timeout(200)
    head=page.locator('#rchTable thead').inner_text()
    for c in ['条目号','物质名称','CAS / EC','列入原因','最迟申请日期','日落日期','授权用途或豁免','当前状态','来源版本']:
        ok(c in head,'列表含「%s」列'%c)
    ok(page.locator('#rchTable tbody tr').count()==6,'授权清单 6 条示例')
    page.evaluate("(x)=>rchXivDrawer(x)",'2');page.wait_for_timeout(250)
    dw=page.locator('#rchDw').inner_text()
    ok('日落日期' in dw and '未经授权不得在欧盟境内使用' in dw,'抽屉说明日落日期法律后果')
    page.evaluate("()=>rchDrawerClose()")

    print('\n=== Tab4 Annex XVII 限制清单 ===')
    page.evaluate("()=>{_rchF.xvii={kw:'',obj:'',type:''};rchGoTab('xvii');}");page.wait_for_timeout(200)
    head=page.locator('#rchTable thead').inner_text()
    for c in ['限制条目号','物质或物质组','CAS / EC','适用对象','限制类型','限制用途','浓度阈值','生效日期','豁免条件','限制条件摘要','来源版本']:
        ok(c in head,'列表含「%s」列'%c)
    ok(page.locator('#rchTable tbody tr').count()==8,'限制条目 8 条示例（非 CAS 黑名单）')
    tb=page.locator('#rchTable tbody').inner_text()
    ok('—（本条不设浓度阈值，只禁用途）' in tb,'存在只禁用途、不设浓度阈值的条目（阈值可为空）')
    ok('物品' in tb and '物质组' in tb,'体现适用对象与物质组口径')
    page.select_option('#rchXvObj','物品');page.wait_for_timeout(150)
    ok(page.locator('#rchTable tbody tr').count()==3,'按适用对象（物品）筛选 3 条')
    page.select_option('#rchXvObj','');page.wait_for_timeout(120)
    page.evaluate("(x)=>rchXviiDrawer(x)",'Entry 77');page.wait_for_timeout(250)
    dw=page.locator('#rchDw').inner_text()
    ok('可能命中限制' in dw and '适用对象' in dw and '浓度' in dw and '豁免条件' in dw,'抽屉写明「可能命中限制」与用途 / 浓度 / 豁免三要素')
    page.evaluate("()=>rchDrawerClose()")

    print('\n=== Tab5 Annex XIII PBT/vPvB 判定规则卡片 ===')
    page.evaluate("()=>rchGoTab('pbt')");page.wait_for_timeout(250)
    ok(page.locator('.rch-rule').count()==9,'规则卡片 9 条')
    cards=page.locator('#rchRuleBox').inner_text()
    ok('BCF > 2000' in cards and 'BCF > 5000' in cards,'含水生生物累积与极高累积阈值')
    ok('log Kow > 4.5' in cards and 'NOEC' in cards,'含 log Kow 与长期 NOEC 判定条件')
    ok('综合判定' in cards and 'PBT' in cards and 'vPvB' in cards,'含 PBT / vPvB 综合判定规则')
    ok('本次不实现真实判定计算' in page.locator('#rchTabBody').inner_text(),'页面注明不实现真实判定计算')
    page.locator('.rch-rule').first.click();page.wait_for_timeout(250)
    dw=page.locator('#rchDw').inner_text()
    ok('研发实现用' in dw and '所需输入' in dw and '法规出处' in dw and '审核状态' in dw,'判定规则抽屉含输入 / 条件 / 输出 / 出处 / 审核状态')
    page.evaluate("()=>rchDrawerClose()")

    print('\n=== Tab6 版本变更与影响（规划口径） ===')
    page.evaluate("()=>rchGoTab('chg')");page.wait_for_timeout(250)
    body=page.locator('#rchTabBody').inner_text()
    ok('规划能力' in body and '当前为静态演示，未接入联网监控' in body and '必须经法规专员审核后发布' in body,'规划能力口径与原文案一致')
    ok('监控来源（规划）' in body and 'EUR-Lex / Cellar' in body,'展示监控来源（规划）与最近检查时间')
    ok('待审核' in body,'展示审核状态')
    head=page.locator('#rchTable thead').inner_text()
    for c in ['受影响模块','新旧条文差异摘要','模板修改建议','影响物质数','影响配方数','影响 SDS 数']:
        ok(c in head,'列表含「%s」列'%c)
    tb=page.locator('#rchTable tbody').inner_text()
    ok('示例' in tb and '官方清单' in tb,'影响数量分别标注官方清单 / 示例')
    page.get_by_role('button',name='查看影响范围').first.click();page.wait_for_timeout(200)
    mb=page.locator('#mBody').inner_text()
    ok('示例数据' in mb and '影响分析能力' in mb,'影响范围弹窗标注示例数据')
    ok('新旧条文差异摘要' in mb and '模板修改建议' in mb,'弹窗展示差异摘要与模板修改建议')
    page.evaluate('closeModal()')

    print('\n=== 跳转法规统一查询（按 lawKey 过滤） ===')
    for lk,cnt in [('svhc',1),('xiv',2),('xvii',3)]:
        page.evaluate("()=>showPage('law:reach')");page.wait_for_timeout(120)
        page.evaluate("(k)=>rchToQuery(k)",lk);page.wait_for_timeout(350)
        ok(page.evaluate('curPage')=='law:query','跳到法规统一查询（%s）'%lk)
        ok(page.evaluate("()=>$('lqLaw').value")==lk,'按 lawKey=%s 预置法规类别筛选'%lk)
        ok(page.locator('#lqTable tbody tr').count()==cnt,'%s 类别命中 %d 条'%(lk,cnt))
    page.evaluate("()=>lawQueryClear()");page.wait_for_timeout(150)
    ok(page.evaluate("()=>$('lqLaw').value")=='' and page.locator('#lqTable tbody tr').count()==18,'重置后恢复全量 18 条')

    print('\n=== 导入新版本向导（静态演示） ===')
    page.evaluate("()=>showPage('law:reach')");page.wait_for_timeout(250)
    page.evaluate("()=>rchImport()");page.wait_for_timeout(200)
    steps=page.locator('#mBody .mini-step').all_text_contents()
    ok(len(steps)==5 and all(any(s in x for s in ['登记来源文件','创建新版本','上传结构化数据','查看变更','审核发布']) for x in steps),'向导五步与 CLP 页口径一致：%s'%' / '.join(steps))
    page.evaluate("()=>rchImpNext(2)");page.wait_for_timeout(120)
    page.fill('#riVer','V2026.3')
    page.evaluate("()=>rchImpNext(3)");page.wait_for_timeout(120)
    page.evaluate("()=>rchImpPickDemo()");page.wait_for_timeout(100)
    page.evaluate("()=>rchImpNext(4)");page.wait_for_timeout(150)
    mb=page.locator('#mBody').inner_text()
    ok('新增条目' in mb and '修改条目' in mb and '删除条目' in mb,'变更预览覆盖新增 / 修改 / 删除')
    ok('必须经人工逐条核对确认' in mb,'预览强调人工核对')
    page.evaluate("()=>rchImpImpact()");page.wait_for_timeout(180)
    ok('示例数据' in page.locator('#mBody').inner_text(),'向导内影响范围同样标注示例')
    page.evaluate("closeModal()");page.wait_for_timeout(100)
    page.evaluate("()=>rchImpNext(5)");page.wait_for_timeout(120)
    page.evaluate("()=>$('riOk').checked=true")
    n0=page.evaluate("()=>REACH_CHANGES.length")
    page.evaluate("()=>rchImpPublish()");page.wait_for_timeout(300)
    ok(page.evaluate("()=>REACH_CHANGES.length")==n0+1,'发布后变更记录 +1')
    ok(page.evaluate('()=>_rchTab')=='chg','发布后定位到版本变更 Tab')

    print('\n=== RoHS 限用物质页（受限物质管理） ===')
    page.evaluate("()=>showPage('law:rohs')");page.wait_for_timeout(300)
    ok(page.locator('#rohsTable tbody tr').count()==10,'直接列全 10 条受限物质（非空占位页）')
    rt=page.locator('#pageHost').inner_text()
    head=page.locator('#rohsTable thead').inner_text()
    for c in ['物质名称','中文名','CAS','EC','限值','适用对象','数据版本']:
        ok(c in head,'列表含「%s」列'%c)
    ok('7439-92-1' in rt and '7440-43-9' in rt and '18540-29-9' in rt,'覆盖 4 种重金属（铅 / 镉 / 六价铬等）')
    ok('0.01%（100 ppm）' in rt,'镉限值 0.01%（其余 0.1%）口径正确')
    ok('均质材料' in rt and '重量百分比' in rt,'限值口径写明均质材料中重量百分比')
    ok(rt.count('物质组，无单一 CAS / EC')>=2,'PBBs / PBDEs 标注物质组、无单一 CAS')
    ok('电子电气设备（EEE）' in rt,'适用对象写明电子电气设备')
    ok('Directive 2011/65/EU Annex II' in rt and '2015/863' in rt,'来源与修订指令写明')
    ok('没有官方结构化数据下载' in rt and '人工维护一份 10 行的结构化数据表' in rt,'人工维护方式说明（区别于批量导入）')
    ok('豁免项见指令附录 III / IV，本页仅列附录 II 受限物质' in rt,'豁免口径声明完整')
    ok('查看豁免清单' in rt,'预留「查看豁免清单」入口')
    ok('中国 RoHS 为独立体系' in rt and '待业务确认' in rt,'中国 RoHS 标注为独立体系、是否纳入待确认')
    page.fill('#rohsKw','117-81-7');page.wait_for_timeout(150)
    ok(page.locator('#rohsTable tbody tr').count()==1,'支持按 CAS 搜索')
    page.fill('#rohsKw','');page.wait_for_timeout(120)
    page.select_option('#rohsGrp','邻苯二甲酸酯');page.wait_for_timeout(150)
    ok(page.locator('#rohsTable tbody tr').count()==4,'按物质类别筛选（邻苯二甲酸酯 4 条）')
    page.select_option('#rohsGrp','');page.wait_for_timeout(150)
    page.get_by_role('button',name='查看豁免清单').click();page.wait_for_timeout(200)
    ok('占位' in page.locator('#mBody').inner_text() and '附录 III' in page.locator('#mBody').inner_text(),'豁免清单入口为占位说明')
    page.evaluate('closeModal()')

    print('\n=== 职业接触限值（OEL）入口（深度覆盖见 smoke_oel.py） ===')
    page.evaluate("()=>showPage('law:oel')");page.wait_for_timeout(300)
    ot=page.locator('#pageHost').inner_text()
    ok(page.evaluate('curPage')=='law:oel','law:oel 可正常进入（路由沿用）')
    ok('职业接触限值（OEL）' in ot and '本期仅占位' not in ot,'OEL 已升级为维护页面，不再是占位页')
    ok('数据集版本' in ot and '限值明细' in ot,'OEL 页面已含数据集版本与限值明细')

    print('\n=== 运输法规库（law:trans 占位 · 多运输方式） ===')
    page.evaluate("()=>showPage('law:trans')");page.wait_for_timeout(250)
    tt=page.locator('#pageHost').inner_text()
    ok('数据源待确认、本期仅占位' in tt,'标注数据源待确认、本期仅占位')
    ok('UN TDG' in tt and 'IMDG' in tt and 'IATA' in tt and 'GB 6944' in tt and 'GB 12268' in tt,'列明各运输方式适用规则')
    ok(page.locator('.law-card').count()==4,'以 4 张卡片体现「多运输方式」')
    ok('独立的法规体系' in tt and 'CLP 只管分类与标签、不管运输' in tt,'写明运输属独立法规体系')
    ok('SDS 第 14 章' in tt,'写明与 SDS 第 14 章的联动')

    print('\n=== 表述红线 ===')
    page.evaluate("()=>showPage('law:reach')");page.wait_for_timeout(200)
    page.evaluate("()=>rchGoTab('chg')");page.wait_for_timeout(200)
    alltxt=page.locator('#pageHost').inner_text()
    ok('已实现自动监控' not in alltxt and '已实现自动发现' not in alltxt and '自动解析' not in alltxt,'无「已实现自动监控 / 自动解析」类表述')
    ok('未接入联网监控' in alltxt,'明确标注当前未接入联网监控')

    print('\n=== 运行时 ===')
    ok(not errors,'REACH / RoHS / 占位页流程 JavaScript 错误为 0'+(('：'+errors[0]) if errors else ''))
    browser.close()

print('=== 结果：通过 %d / 失败 %d ==='%(passed,failed))
raise SystemExit(1 if failed else 0)
